/**
 * Catálogo canônico — alinhado com APIMOBEPI/src/config/nomenclature.config.js
 */
export const NOMENCLATURE_KEYS = {
  menu: {
    dashboard: 'menu.dashboard',
    colaboradores: 'menu.colaboradores',
    empresas: 'menu.empresas',
    funcoes: 'menu.funcoes',
    epi: 'menu.epi',
    tipos_epi: 'menu.tipos_epi',
    variantes_epi: 'menu.variantes_epi',
    regras_troca: 'menu.regras_troca',
    intercorrencias: 'menu.intercorrencias',
    agenda_trocas: 'menu.agenda_trocas',
    historico: 'menu.historico',
    usuarios: 'menu.usuarios',
    section: 'menu.section',
    relatorios: 'menu.relatorios',
    configuracoes: 'menu.configuracoes',
  },
  page: {
    dashboard: 'page.dashboard',
    colaboradores: 'page.colaboradores',
    colaboradores_novo: 'page.colaboradores.novo',
    empresas: 'page.empresas',
    funcoes: 'page.funcoes',
    epis: 'page.epis',
    tipos_epi_novo: 'page.tipos_epi.novo',
    variantes_epi: 'page.variantes_epi',
    variantes_epi_novo: 'page.variantes_epi.novo',
    regras_troca: 'page.regras_troca',
    intercorrencias: 'page.intercorrencias',
    agenda_trocas: 'page.agenda_trocas',
    agenda_trocas_calendario: 'page.agenda_trocas.calendario',
    historico: 'page.historico',
    relatorios: 'page.relatorios',
    relatorios_detalhe: 'page.relatorios.detalhe',
    usuarios: 'page.usuarios',
    usuarios_novo: 'page.usuarios.novo',
    section_list: 'page.section.list',
    section_create: 'page.section.create',
    section_edit: 'page.section.edit',
    configuracoes: 'page.configuracoes',
    app_default: 'page.app_default',
    subtitle_dashboard: 'page.subtitle.dashboard',
    subtitle_colaboradores: 'page.subtitle.colaboradores',
    subtitle_colaboradores_novo: 'page.subtitle.colaboradores.novo',
    subtitle_funcoes: 'page.subtitle.funcoes',
    subtitle_empresas: 'page.subtitle.empresas',
    subtitle_tipos_epi: 'page.subtitle.tipos_epi',
    subtitle_tipos_epi_novo: 'page.subtitle.tipos_epi.novo',
    subtitle_variantes_epi: 'page.subtitle.variantes_epi',
    subtitle_variantes_epi_novo: 'page.subtitle.variantes_epi.novo',
    subtitle_regras_troca: 'page.subtitle.regras_troca',
    subtitle_intercorrencias: 'page.subtitle.intercorrencias',
    subtitle_agenda_trocas: 'page.subtitle.agenda_trocas',
    subtitle_agenda_trocas_calendario: 'page.subtitle.agenda_trocas.calendario',
    subtitle_historico: 'page.subtitle.historico',
    subtitle_relatorios: 'page.subtitle.relatorios',
    subtitle_usuarios: 'page.subtitle.usuarios',
    subtitle_usuarios_novo: 'page.subtitle.usuarios.novo',
    subtitle_section_list: 'page.subtitle.section.list',
    subtitle_section_create: 'page.subtitle.section.create',
    subtitle_section_edit: 'page.subtitle.section.edit',
    subtitle_configuracoes: 'page.subtitle.configuracoes',
    subtitle_consumo: 'page.subtitle.consumo',
    subtitle_matriz: 'page.subtitle.matriz',
  },
  entity: {
    colaborador_singular: 'entity.colaborador.singular',
    colaborador_plural: 'entity.colaborador.plural',
    funcao_singular: 'entity.funcao.singular',
    funcao_plural: 'entity.funcao.plural',
    epi_singular: 'entity.epi.singular',
    epi_plural: 'entity.epi.plural',
    section_singular: 'entity.section.singular',
    section_plural: 'entity.section.plural',
    section_compound: 'entity.section.compound',
    unidade_singular: 'entity.unidade.singular',
    unidade_plural: 'entity.unidade.plural',
    usuario_singular: 'entity.usuario.singular',
    usuario_plural: 'entity.usuario.plural',
    regra_troca_singular: 'entity.regra_troca.singular',
    regra_troca_plural: 'entity.regra_troca.plural',
    intercorrencia_singular: 'entity.intercorrencia.singular',
    intercorrencia_plural: 'entity.intercorrencia.plural',
  },
  action: {
    new: 'action.new',
    new_section: 'action.new_section',
    save: 'action.save',
    cancel: 'action.cancel',
    edit: 'action.edit',
    delete: 'action.delete',
    search: 'action.search',
  },
  message: {
    section_loading: 'message.section.loading',
    section_empty: 'message.section.empty',
    section_save_success: 'message.section.save_success',
  },
  scope: {
    global: 'scope.global',
    company: 'scope.company',
    section: 'scope.section',
    role: 'scope.role',
    employee: 'scope.employee',
  },
} as const;

export type NomenclatureKey = typeof NOMENCLATURE_KEYS[keyof typeof NOMENCLATURE_KEYS][keyof typeof NOMENCLATURE_KEYS[keyof typeof NOMENCLATURE_KEYS]];

/** Defaults espelhados do backend (fallback offline) */
export const NOMENCLATURE_DEFAULTS: Record<string, string> = {
  'menu.dashboard': 'Dashboard',
  'menu.colaboradores': 'Colaboradores',
  'menu.empresas': 'Empresas',
  'menu.funcoes': 'Gestão de Funções',
  'menu.epi': 'EPI',
  'menu.tipos_epi': 'Tipo de EPIs',
  'menu.variantes_epi': 'Variantes de EPIs',
  'menu.regras_troca': 'Regras de Troca',
  'menu.intercorrencias': 'Intercorrências',
  'menu.agenda_trocas': 'Agenda de Trocas',
  'menu.historico': 'Histórico',
  'menu.usuarios': 'Usuários',
  'menu.section': 'Seção',
  'menu.relatorios': 'Relatórios',
  'menu.configuracoes': 'Configurações',
  'page.dashboard': 'Visão Geral do Sistema',
  'page.colaboradores': 'Gestão de Colaboradores',
  'page.colaboradores.novo': 'Novo Colaborador',
  'page.empresas': 'Cadastro de Empresas',
  'page.funcoes': 'Gestão de Funções',
  'page.epis': 'Tipo de EPIs',
  'page.tipos_epi.novo': 'Novo Tipo de EPI',
  'page.variantes_epi': 'Variantes de EPIs',
  'page.variantes_epi.novo': 'Nova Variante de EPI',
  'page.regras_troca': 'Regras de Substituição',
  'page.intercorrencias': 'Intercorrências (Inconsistências e Fraudes)',
  'page.agenda_trocas': 'Agenda de Trocas Programadas',
  'page.agenda_trocas.calendario': 'Calendário de Trocas',
  'page.historico': 'Histórico e Rastreabilidade Jurídica',
  'page.relatorios': 'Relatórios e BI',
  'page.relatorios.detalhe': 'Relatório',
  'page.usuarios': 'Usuários',
  'page.usuarios.novo': 'Novo Usuário',
  'page.section.list': 'Seção',
  'page.section.create': 'Cadastrar Seção',
  'page.section.edit': 'Editar Seção',
  'page.configuracoes': 'Configurações do Sistema',
  'page.app_default': 'EPI Control',
  'page.subtitle.dashboard': 'Indicadores operacionais e de conformidade do controle de EPIs.',
  'page.subtitle.colaboradores': 'Cadastro, vínculos e gestão dos colaboradores da empresa.',
  'page.subtitle.colaboradores.novo': 'Preencha os dados para cadastrar um novo colaborador.',
  'page.subtitle.funcoes': 'Definição de funções, riscos ocupacionais e EPIs obrigatórios.',
  'page.subtitle.empresas': 'Cadastro operacional para vínculo de colaboradores. Integração ERP fica em Configurações.',
  'page.subtitle.tipos_epi': 'Cadastre os tipos de EPI. Variantes homologadas ficam em Variantes de EPIs.',
  'page.subtitle.tipos_epi.novo': 'Cadastre um novo tipo de EPI para vincular em funções e matriz.',
  'page.subtitle.variantes_epi': 'Variantes homologadas vinculadas aos tipos de EPI.',
  'page.subtitle.variantes_epi.novo': 'Cadastre fabricante, modelo e CA da variante homologada.',
  'page.subtitle.regras_troca': 'Vida útil padrão por tipo e regras de substituição por escopo.',
  'page.subtitle.intercorrencias': 'Inconsistências e possíveis fraudes identificadas pela Inteligência de Dados.',
  'page.subtitle.agenda_trocas': 'Planejamento preventivo de substituição de EPIs por vencimento.',
  'page.subtitle.agenda_trocas.calendario': 'Visualização mensal, semanal e diária das trocas programadas.',
  'page.subtitle.historico': 'Rastreabilidade completa de todas as movimentações de EPI.',
  'page.subtitle.relatorios': 'Análise de dados e exportação de indicadores de segurança.',
  'page.subtitle.usuarios': 'Gestão de logins, perfis de acesso e permissões do sistema.',
  'page.subtitle.usuarios.novo': 'Preencha os dados para cadastrar um novo usuário.',
  'page.subtitle.section.list': 'Cadastro de setores e unidades operacionais.',
  'page.subtitle.section.create': 'Informe os dados da seção e vincule os EPIs obrigatórios.',
  'page.subtitle.section.edit': 'Atualize os dados da seção e os EPIs vinculados.',
  'page.subtitle.configuracoes': 'Gerencie acessos, integrações e sua conta.',
  'page.subtitle.consumo': 'Acompanhamento do fluxo de entregas e trocas de EPI (últimos 30 dias).',
  'page.subtitle.matriz': 'Cruzamento obrigatório função x EPI para conformidade jurídica.',
  'entity.colaborador.singular': 'Colaborador',
  'entity.colaborador.plural': 'Colaboradores',
  'entity.funcao.singular': 'Função',
  'entity.funcao.plural': 'Funções',
  'entity.epi.singular': 'EPI',
  'entity.epi.plural': 'EPIs',
  'entity.section.singular': 'Seção',
  'entity.section.plural': 'Seções',
  'entity.section.compound': 'Setor / Seção',
  'entity.unidade.singular': 'Unidade',
  'entity.unidade.plural': 'Unidades',
  'entity.usuario.singular': 'Usuário',
  'entity.usuario.plural': 'Usuários',
  'entity.regra_troca.singular': 'Regra de Troca',
  'entity.regra_troca.plural': 'Regras de Troca',
  'entity.intercorrencia.singular': 'Intercorrência',
  'entity.intercorrencia.plural': 'Intercorrências',
  'action.new': 'Novo',
  'action.new_section': 'Nova Seção',
  'action.save': 'Salvar',
  'action.cancel': 'Cancelar',
  'action.edit': 'Editar',
  'action.delete': 'Excluir',
  'action.search': 'Buscar',
  'message.section.loading': 'Carregando setores...',
  'message.section.empty': 'Nenhum setor encontrado.',
  'message.section.save_success': 'Setor salvo com sucesso.',
  'scope.global': 'Global',
  'scope.company': 'Empresa',
  'scope.section': 'Setor',
  'scope.role': 'Função',
  'scope.employee': 'Colaborador',
};

/** Ordem de exibição no dicionário de termos (alinhado com nomenclature.config.js) */
export const NOMENCLATURE_GROUP_ORDER = [
  'Menu',
  'Páginas',
  'Relatórios',
  'Escopos',
  'Entidades',
  'Ações',
  'Mensagens',
] as const;

export function compareNomenclatureGroups(a: string, b: string): number {
  const index = (group: string) => {
    const i = (NOMENCLATURE_GROUP_ORDER as readonly string[]).indexOf(group);
    return i === -1 ? NOMENCLATURE_GROUP_ORDER.length : i;
  };
  const byOrder = index(a) - index(b);
  if (byOrder !== 0) return byOrder;
  return a.localeCompare(b, 'pt-BR');
}
